Website redesign
rhino-linux/website pull request #25
Opened 2023-05-30 11:41 UTC by ajstrongdev

- upd(*): Minor website redesigns + Add bug tracker / better news feed
- add blobs
- blur blobs
- Update style.css
- revert blobs
- make header awesome
- update the news feed page
- upd style for feed
- wiki
- footer
- fix box
- New homescreen yay
- Fix: website scaling

2023-05-30 11:41 UTC, ajstrongdev commented
@oklopfer Review this, Don't merge this time :rofl:

2023-05-30 14:58 UTC, oklopfer requested changes

2023-05-30 14:58 UTC, oklopfer commented on index.html
> +                <img src="assets/images/rhino-pkg.png" class="mob-show" alt="Rhino Setup" width="100%"/>
wrong alt

2023-05-30 16:04 UTC, ajstrongdev commented on index.html
> +                <img src="assets/images/rhino-pkg.png" class="mob-show" alt="Rhino Setup" width="100%"/>
Wdym

2023-05-30 16:05 UTC, ajstrongdev commented on index.html
> +                    Finally, we don’t do any mandatory data collection. You can opt-in with rhino-setup to having apport installed on your system, to send crash and bug reports directly to developers
It makes more sense to keep it under the "user have control" section

2023-05-30 16:42 UTC, oklopfer commented on index.html
> +                <img src="assets/images/rhino-pkg.png" class="mob-show" alt="Rhino Setup" width="100%"/>
You set a bunch of images with the alt "Rhino Setup", even though only one of them is.

2023-05-30 16:43 UTC, oklopfer commented on index.html
> +                <img src="assets/images/rhino-linux.png" class="mob-show" alt="Rhino Setup" width="100%"/>
This is a bad solution. You should just be using css's screen size limits.

2023-05-30 16:44 UTC, oklopfer commented on index.html
> +                    Finally, we don’t do any mandatory data collection. You can opt-in with rhino-setup to having apport installed on your system, to send crash and bug reports directly to developers
Maybe, but not with the way it's worded, and it also breaks how the rest of the page looks. It should either be rewritten and incorporated into the previous paragraph, or be put as it's own line at the end.

2023-05-30 21:30 UTC, ajstrongdev commented on index.html
> +                <img src="assets/images/rhino-pkg.png" class="mob-show" alt="Rhino Setup" width="100%"/>
I see.

2023-05-30 21:30 UTC, ajstrongdev commented on index.html
> +                <img src="assets/images/rhino-linux.png" class="mob-show" alt="Rhino Setup" width="100%"/>
Got it, will fix later

2023-05-30 21:31 UTC, ajstrongdev commented on index.html
> +                    Finally, we don’t do any mandatory data collection. You can opt-in with rhino-setup to having apport installed on your system, to send crash and bug reports directly to developers
I disagree and think it's fine as-is personally.

2023-05-30 22:50 UTC, oklopfer commented on index.html
> +                    Finally, we don’t do any mandatory data collection. You can opt-in with rhino-setup to having apport installed on your system, to send crash and bug reports directly to developers
ill concede on this one if you fix the other 2

2023-06-01 11:15 UTC, ajstrongdev commented on assets/css/style.css
> +}
Headers are correct size but they now overlap when window size is full-screen

2023-06-01 11:23 UTC, ajstrongdev commented
The non-mandatory data collection text needs to be centred

The text for why rhino Linux ideally should be at 60vw, with the images and side-by-side text being 90vw.

2023-06-01 19:00 UTC, oklopfer approved these changes

2023-06-01 19:04 UTC, oklopfer commented
closing in favor of https://github.com/rhino-linux/website/pull/27

2023-06-01 19:04 UTC, closed without merging