web: release info for 2023.4
rhino-linux/website pull request #56
Opened 2023-12-08 16:09 UTC by ajstrongdev

- [ ] Update download mirrors
- [ ] Update download page information
- [ ] Write release notes
- [ ] Modify news page
- [ ] Add banner across homepage

2023-12-14 19:23 UTC, ajstrongdev commented
Release notes are finished

2023-12-18 01:29 UTC, oklopfer commented
Add to release notes:
- rhino-core/rhino-pine-core/rhino-ubxi-core/rhino-server-core are now set as essential packages
- rhino-system light mode bug fixed
- connecting to wifi on embedded fixed
- pacstall-qa introduced as a new default package
- rhino-setup is now properly on the system at post-install
- kernels 6.6.7-generic, 6.7.0-rc5-okpine, 6.5.0-raspi

2023-12-18 01:30 UTC, oklopfer requested changes

2023-12-18 01:30 UTC, oklopfer commented on news-10.html
> +    We also plan to create a Linux kernel management application. This application will allow for you to change between different versions of the linux kernel, an example of this could be switching t
no we dont, this is called mainline and it exists.

2023-12-18 01:33 UTC, oklopfer requested changes

2023-12-18 01:33 UTC, oklopfer commented on news-10.html
> +    Some other things to expect in 2024 would be support for offline installations, as well as improved documentation.
- offline installions
- updated wiki pages
- prospects of wayland
- ubxi ports
- rhino-pkg rewrite in nushell
- pacstall 5.0.0, which will bring significantly closer pacscript parity to PKGBUILDs
most of these can be broken out into their own bullet points, too.

2023-12-18 01:34 UTC, oklopfer requested changes

2023-12-18 01:34 UTC, oklopfer commented on news-10.html
> +  </p>
Add to release notes:
- rhino-core/rhino-pine-core/rhino-ubxi-core/rhino-server-core are now set as essential packages
- rhino-system light mode bug fixed
- connecting to wifi on embedded fixed
- pacstall-qa introduced as a new default package
- rhino-setup is now properly on the system at post-install
- kernels 6.6.7-generic, 6.7.0-rc5-okpine, 6.5.0-raspi

2023-12-18 01:40 UTC, oklopfer requested changes

2023-12-18 01:40 UTC, oklopfer commented on news-10.html
> +    Ending the year - Rhino Linux 2023.4
Rhino Linux 2023.4 - End of year wrap-up and major stability improvements

2023-12-18 01:40 UTC, oklopfer commented on news.html
> +                        Rhino Linux 2023.4: Enhancing the experience
Experience

2023-12-18 01:40 UTC, oklopfer commented on news-10.html
> +  </p>
explain what pacstall-qa is too

2023-12-18 20:04 UTC, ajstrongdev commented on news-10.html
> +    We also plan to create a Linux kernel management application. This application will allow for you to change between different versions of the linux kernel, an example of this could be switching t
Hm, that app doesn't have functionality with the pacscripts we install, perhaps we could create a fork of it instead. + I'd want it done in libadwaita if we're shipping it with the distribution anyway.

2023-12-18 20:04 UTC, ajstrongdev commented on news-10.html
> +    Some other things to expect in 2024 would be support for offline installations, as well as improved documentation.
Got it, will fix

2023-12-19 02:34 UTC, oklopfer requested changes

2023-12-19 02:34 UTC, oklopfer commented on news-10.html
> +    &bull; Pacstall 4.3.0 released, meaning that packages can now be tagged as "essential", and as such cannot be removed from the system. The rhino-core package, and its varients are now tagged as e
this needs to be worked on. I will look over it tomorrow

2023-12-19 12:29 UTC, ajstrongdev commented on news-10.html
> +    &bull; Pacstall 4.3.0 released, meaning that packages can now be tagged as "essential", and as such cannot be removed from the system. The rhino-core package, and its varients are now tagged as e
In what way?

2023-12-19 16:46 UTC, oklopfer commented on news-10.html
> +    &bull; Pacstall 4.3.0 released, meaning that packages can now be tagged as "essential", and as such cannot be removed from the system. The rhino-core package, and its varients are now tagged as e
Beginning with Pacstall 4.3.0, packages may now use Debian’s `priority` flag. As such, `rhino-core` and variants are now tagged `essential`, marking them unremovable to the system. Additionally, Unicorn will no longer automatically be removed when switching between the `rhino*-core` family. To remove `unicorn-desktop` or `unicorn-mobile`, users must first switch to `rhino-ubxi-core` or `rhino-server-core`; they will then be able to safely remove the package. This step is also needed if one is switching between `rhino-core` and `rhino-pine-core`.

2023-12-19 19:46 UTC, oklopfer requested changes

2023-12-19 19:46 UTC, oklopfer commented on news-10.html
> +    This development period was substantially longer than our previous releases, this can be attributed to the start of a new semester. If you wish to contribute to Rhino Linux and help us push out a
which can be attributed to

2023-12-19 19:46 UTC, oklopfer commented on news-10.html
> +    Rhino-pkg will be getting a full overhaul in nushell.
`rhino-pkg` in lowercase + code style

Also, let's rephrase:

`rhino-pkg` is in the process of being rewritten in nushell. This change will be a complete overhaul of the program, aiming to make it faster, more accurate, more precise, and introducing several new functions, like the ability to sync repositories without upgrading, display descriptions in search results, and more.

2023-12-19 19:46 UTC, oklopfer commented on news-10.html
> +    &bull; Changes in Nala v0.14.0 have affected how upgrades are handled. As a result, rhino-pkg now passes <code class="text-off-white bg-site-200 rounded-[0.65em] p-1 border-rhino-purple border-2"
No. Just keep it simple, and add a second bullet:

- If Nala is installed, `rhino-pkg update` no longer auto-removes packages by default. 

- To clean up unneeded packages or broken dependencies on a system, users can run the new `rhino-pkg cleanup` command. 


Also, move the 4.3.0/priority thing up to this (the rhino-pkg) section.

2023-12-19 19:46 UTC, oklopfer commented on news-10.html
> +    Other changes
Split up Features and Bug Fixes.

2023-12-19 19:46 UTC, oklopfer commented on news-10.html
> +    &bull; <a href="https://github.com/rhino-linux/unicorn/issues/39" class="text-rhino-purple">Unicorn #39</a> has finally been merged, bringing optional auto-tiling to the Unicorn Desktop. Kick sta
Unicorn #39 has finally been merged, bringing optional auto-tiling to Unicorn. After updating and rebooting, a new applet will appear in the top right section of the panel. To kick start your tiling window experience, you can select the new applet, which will bring up a toggle to enable/disable tiling mode.

2023-12-19 19:46 UTC, oklopfer commented on news-10.html
> +    &bull; Modem stability fixes have been shipped to both the PinePhone and the PinePhone Pro, as well as GPS support enablement
end this with a period

2023-12-19 19:46 UTC, oklopfer commented on news-10.html
> +    &bull; We have managed to close an open issue, where bluetooth support would be hit-and-miss on certain devices, this has now been resolved.
No,: 

An issue regarding Bluetooth support has been resolved, with our full transition from `pulseaudio` to `pipewire`.

2023-12-19 19:46 UTC, oklopfer commented on news-10.html
> +    &bull; A bug with our auto-tiling implementation (utilising cortile) and conky has been resolved.
Nope. conky was a user installed package. We did not fix anything. They fixed their own issue by editing their conky config. Remove this entirely, we did nothing.

2023-12-19 19:46 UTC, oklopfer commented on news-10.html
> +    &bull; The installed kernels for this release are 6.6.7-generic for desktop, 6.7.0-rc5-okpine on Pine64 devices and 6.5.0-raspi for Raspberry Pi.
Make the versions in code style

2023-12-19 19:46 UTC, oklopfer commented on news-10.html
> +    Pacstall 5.0.0 should release in 2024, which will bring significantly closer pacscript parity to PKGBUILDs.
Pacstall 5.0.0 *will* be releasing in 2024,

2023-12-19 19:46 UTC, oklopfer commented on news-10.html
> +    There are also prospects of Unicorn becoming available on Wayland in 2024.
Nope. Here: 

We are still exploring the prospects of Unicorn switching to Wayland in the future. Progress on `xfwm4-wayland` has not moved for the majority of our development this year, and so we are considering alternative compositing options. UBXI projects may help largely with this process, so we encourage you to contribute!

2023-12-19 19:46 UTC, oklopfer commented on news-10.html
> +    Some other things to expect in 2024 would be support for offline installations, as well as improved documentation on our <a href="wiki.html" class="text-rhino-purple">Rhino Linux wiki</a>.
...to expect in 2024 *are* support for offline installations...

not "would be"

2023-12-19 20:12 UTC, oklopfer requested changes

2023-12-19 20:12 UTC, oklopfer commented on news-10.html
> +    &bull; If Nala is installed, <code class="text-off-white bg-site-200 rounded-[0.65em] p-1 border-rhino-purple border-2">rhino-pkg update</code> update no longer auto-removes packages by default.
rhino-pkg update update 😐

Also these should be two separate paragraph blocks if they're two separate bullets, just like everyone else.

2023-12-19 20:12 UTC, oklopfer commented on news-10.html
> +    &bull; An issue regarding Bluetooth support has been resolved, with our full transition from pulseaudio to pipewire.
pulse and pipe should be in code style.

2023-12-19 20:12 UTC, oklopfer commented on news-10.html
> +    &bull; pacstall-qa is now introduced as a new default package. pacstall-qa is a tool developed by Pacstall as a tool to test pascripts from PR's locally. You can read more about pacstall-qa <a hr
put pacstall-qa in code style.

2023-12-19 20:12 UTC, oklopfer commented on news-10.html
> +    &bull; The "Your System" application only displaying in light mode bug has been fixed.
The bug causing the "Your System" application to be stuck in light mode has finally been resolved.

2023-12-19 20:15 UTC, oklopfer requested changes

2023-12-19 20:15 UTC, oklopfer commented on news-10.html
> +  </p>``
Stray ``

2023-12-20 14:12 UTC, merged