add: new blog post
rhino-linux/website pull request #62
Opened 2024-06-24 21:42 UTC by ajstrongdev

2024-06-24 21:43 UTC, ajstrongdev commented on news-13.html
> +    Before we get into information about this release, we have a brief update about our organizational structure. As we mentioned <a href="news-11.html" class="text-rhino-purple">a while ago</a>, dev
Typo in last post

2024-06-28 17:38 UTC, oklopfer requested changes

2024-06-28 17:38 UTC, oklopfer commented on news-14.html
> +    With our contributor's code of conduct, we aim to provide a safe and welcoming environment for all contributors. We want to ensure that everyone feels welcome and that their contributions are val
it should NOT be hosted on crypt pad, it should have its own page here

2024-06-28 17:38 UTC, oklopfer commented on news-14.html
> +    Our decision to rewrite our website in React is going to provide us with significantly better tools when it comes to managing our documentation, publishing blog posts and ensuring long-term maint
do people really need to know what language we are rewriting our website in? seems like we should just announce that the website is going to get a significant rework.

2024-06-28 17:38 UTC, oklopfer commented on news-14.html
> +    We currently do not have any plans to move development discussions away from Discord at the moment. Discord has been useful as a small team to collaborate on development and communicate effective
this is untrue. we have plans for forums on the new website.

2024-06-28 17:38 UTC, oklopfer commented on news-14.html
> +    &bull; Providing a strong contributor's code of conduct <br>
CCC should all be capitalized

2024-06-28 17:38 UTC, oklopfer requested changes
mission statement?

2024-06-28 17:40 UTC, oklopfer requested changes
mutability should be at the top, not the bottom for the CCC

2024-06-28 22:34 UTC, ajstrongdev commented on news-14.html
> +    Our decision to rewrite our website in React is going to provide us with significantly better tools when it comes to managing our documentation, publishing blog posts and ensuring long-term maint
We can do, however I do not think it's necessarily a problem to mention it either?

2024-06-28 22:35 UTC, ajstrongdev commented on news-14.html
> +    We currently do not have any plans to move development discussions away from Discord at the moment. Discord has been useful as a small team to collaborate on development and communicate effective
My plan would be that the forums would release after the new website. The forums would require significant work that will take much longer than this new website. Hence why I said "at the moment", however I can reword it to include the plans to shift to forums eventually as well.

2024-06-29 00:04 UTC, oklopfer commented on news-14.html
> +    We currently do not have any plans to move development discussions away from Discord at the moment. Discord has been useful as a small team to collaborate on development and communicate effective
> Hence why I said "at the moment", however I can reword it to include the plans to shift to forums eventually as well.
so.... we do have plans to move development discussions away from Discord at the moment. We just are not able to yet.

2024-06-29 13:38 UTC, ajstrongdev commented
Todo:

Add mission statement

2024-07-05 20:30 UTC, oklopfer commented
Where did mutability go

2024-07-06 01:15 UTC, oklopfer approved these changes

2024-07-08 18:26 UTC, merged